# Generated by Django 4.2 on 2024-03-15 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
