# Generated by Django 4.2 on 2024-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='store_id',
            field=models.IntegerField(unique=True),
        ),
    ]
