# Generated by Django 4.2.11 on 2024-03-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
