# Generated by Django 4.2 on 2024-03-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_sale_product_id_alter_sale_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_detail',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit_price',
        ),
    ]
