# Generated by Django 4.2 on 2024-03-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_sale_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='store_location',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transaction_qty',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transaction_time',
        ),
    ]
