# Generated by Django 4.2 on 2024-03-28 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_sale_product_id_remove_sale_store_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_id',
            field=models.IntegerField(),
        ),
    ]
