# Generated by Django 4.2 on 2024-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sale_product_category_sale_product_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='store_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='store_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
